name: Update cards

on:
  schedule:
    - cron: "22 */4 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  update-cards:
    name: Update GitHub stats cards
    runs-on: ubuntu-latest
    needs: update-readme
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&hide_border=true&theme=transparent
          path: cards/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&hide_border=true&theme=transparent
          path: cards/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated cards
        run: |
          if [[ -n $(git diff cards/) ]]; then
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add cards/*.svg
              git commit -m "chore: cards update $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
              git push origin main
          fi
